### ISSUE TITLE
Support next.jdbc

### ISSUE THREAD

**Issue by kanwei** [luminus-framework/conman#66] opened 2019-06-25 00:11 UTC
Would be nice to get a plan to support next.jdbc!

**Comment by yogthos** [comment] 2019-06-25 00:27
That's in the works, basically just waiting for [this issue](https://github.com/layerware/hugsql/issues/96) to get resolved in HugSQL.

**Comment by pablobcb** [comment] 2019-09-23 20:57
looks like the issue is resolved :)

**Comment by yogthos** [comment] 2019-09-23 23:18
Yup, just gotta get around to updating Luminus now. :)

**Comment by vinurs** [comment] 2019-09-28 04:29
does this need to publish a new version that hugsql update to 0.5.1?

**Comment by yogthos** [comment] 2019-09-28 14:21
You're right, I just pushed out a new version of conman `0.8.4` that uses next.jdbc.

**Comment by kanwei** [comment] 2019-09-28 21:18
Unfortunately, the code still refers to clojure.java.jdbc:

```
Syntax error (FileNotFoundException) compiling at (conman/core.clj:1:1).

Could not locate clojure/java/jdbc__init.class, clojure/java/jdbc.clj or clojure/java/jdbc.cljc on classpath.

```

**Comment by kanwei** [comment] 2019-09-28 21:35
I also believe this needs to be excluded in the hugsql dependency to prevent clojure.java.jdbc from loading by default, if we're not explicitly using next.jdbc datasource strings:

```
:exclusions [com.layerware/hugsql-adapter-clojure-java-jdbc]
```

**Comment by yogthos** [comment] 2019-09-28 22:06
Ah you're right, I'll take a look at doing a proper update soonish.

**Comment by csummers** [comment] 2019-10-03 12:28
Just a few notes to help this go more smoothly:

> I also believe this needs to be excluded in the hugsql dependency to prevent clojure.java.jdbc from loading by default, if we're not explicitly using next.jdbc datasource strings:
> 
> ```
> :exclusions [com.layerware/hugsql-adapter-clojure-java-jdbc]
> ```

This is not necessary, but, since the `next.jdbc` adapter is not the default adapter, you need to change the dependencies from the `hugsql` meta clojar to `hugsql-core` + `hugsql-adapter-next-jdbc` and explicitly set the adapter or pass it in as an option to `hugsq/map-of-db-fns`.

```
[com.layerware/hugsql-core "0.5.1"]
[com.layerware/hugsql-adapter-next-jdbc "0.5.1"]
```

```
(ns my-app
  (:require [hugsql.core :as hugsql]
            [hugsql.adapter.next-jdbc :as next-adapter]))

(defn app-init []
  (hugsql/set-adapter! (next-adapter/hugsql-adapter-next-jdbc)))
```
**OR, for conman, it is probably better** to pass in the `:adapter` as an option to the call `hugsql/map-of-db-fns`: http://layerware.github.io/hugsql/hugsql.core.html#var-map-of-db-fns

Also, for anyone using conman w/ `clojure.java.jdbc` for transactions and other options specific to that library, will switching conman over to `next.jdbc` as the default potentially break things?  There might should be some documentation to this effect.

Thanks! :smile:

**Comment by kanwei** [comment] 2019-10-03 19:12
@csummers thanks for the doc - super helpful. Unfortunately I think conman will have to implement the changes, since I was getting a connection error in next.jdbc. I think specifically

```
If you were already creating db-spec as a pooled connection datasource -- a {:datasource ds} hashmap -- then passing (:datasource db-spec) to the next.jdbc functions is the simplest migration path.
```

from https://github.com/seancorfield/next-jdbc/blob/master/doc/migration-from-clojure-java-jdbc.md

**Comment by yogthos** [comment] 2019-10-04 00:35
Yeah, conman has some direct references to clojure.java.jdbc that need to be updated. @nikolap started a branch [here](https://github.com/luminus-framework/conman/tree/next-jdbc), but we ran into a few snags with the test. I'll have to take a closer look at that.

**Comment by pablo-develop** [comment] 2020-01-20 09:37
any updates on this?

**Comment by yogthos** [comment] 2020-01-20 14:47
Not yet, the transaction macro still needs to be updated to work with jdbc.next. I haven't had a chance to look at it unfortunately. If anybody has some time to help with that, would be great.

**Comment by yogthos** [comment] 2020-03-28 15:06
implemented in https://github.com/luminus-framework/conman/pull/68

**Closed as completed by yogthos** 2020-03-28 15:06 UTC
