### ISSUE TITLE
connecting to oracle DB

### ISSUE THREAD

**Issue by hadielmougy** [luminus-framework/conman#35] opened 2017-04-05 11:45 UTC
I'm struggling connecting luminus to oracle db using the following URL
jdbc:oracle:thin:username/password@10.29.10.214:1521:orcl

I'm getting -- Error creating DB connection for jdbc:oracle:thin....

**Comment by yogthos** [comment] 2017-04-05 13:51
The URL I use for oracle is `jdbc:oracle:thin:user/pass@//host:1521/schema`

**Comment by yogthos** [comment] 2017-04-06 19:17
Can we close this one, or are you still having problems connecting? It doesn't appear to be a conman specific issue from what I can tell.

**Comment by yogthos** [comment] 2017-04-08 14:42
I'm going to close the issue for now, since I'm not able to reproduce the error. If you discover there's something conman specific happening we can reopen it.

**Closed as completed by yogthos** 2017-04-08 14:42 UTC
